name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: deno_postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with: 
          deno-version: 1.6.0

      - name: Check formatting
        run: deno fmt --check

      - name: Check lint
        run: deno lint --unstable

      - name: Run tests
        run: deno test --allow-net --allow-env test.ts
